# -*- coding: utf-8 -*-
"""for loop question.pyng

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqtATazDfgCRDd0euMPHK7cWMO0L12qq
"""

num = 10
count = 0
for i in range (1,num+1):
  if(num%i==0):
    count+=1
# print("factor are :",count)
if(count>2):
  print("not primt ",num)
else:
  print("prime")

num = 7
a = 0
for i in range (2,num):
  if(num%i==0):
    a = 1
    break
if(a==1):
  print("not prime ", num)
else:
  print("prime",num)

#q 1
n = int(input("enter a number : "))
for i in range (1,n+1):
  print(i)

#q 2
n = int(input("enter a number : "))
for i in range (n,0,-1):
  print(i)

#q 3
for i in range (97,123):
   print(chr(i) ,end=' ')

#q 4
for i in range(1,101):
  if(i%2==0):
    print(i,end=" ")

#q 5
n = int(input("enter a number : "))
sum = 0
for i in range(1,n+1):
  if(i%2!=0):
    sum +=i
print(sum)

#q 6  = int(input("enter a number : "))
count=0
for digit in str(n):
  if(n>0):
   count+=1
   n = n//10
print(count)

#q 7
n = int(input("enter a number : "))
sum = 0
for digit in str(n):
  if(n>0):
    sum+=n%10
    n= n//10
print(sum)

#q 8
n = int(input("enter a number "))
first_number = 0
last_number = 0
count = 0
temp = n
for digit in str(n):
  if(temp>0):
    count+=1
    temp= temp//10
first_number = n//10**(count-1)
last_number = n%10
print("first_number : " , first_number)
print("last_number : " , last_number)

#q 9
n = int(input("enter a number : "))
sum = 0
count = 0
first_number = 0
last_number= 0
temp = n
for digit in str(n):
  if(temp>0):
    count+=1
    temp = temp//10
first_number = n//10**(count-1)
last_number = n%10
sum = first_number + last_number
print("sum : " , sum)

#q 10
n = int(input("enter a number : "))
rev = 0
for digit in str(n):
  if(n>0):
   rev = rev * 10 + n%10
   n = n//10
print(rev)

#q 11
n = int(input("enter a number : "))
exponent = int(input("enter a number : "))
power = 1
for _ in range (exponent):
    power = power * n
print(n,"^" , exponent , " = " , power)

#q 12
n = int(input("enter a number : "))
for i in range(1,n+1):
  if(n%i==0):
   print(i , end= " ")

#q 13
n = int(input("enter a number : "))
factorial = 1
for i in range(n,0,-1):
  factorial *= i
print(factorial)

#q 15
n = int(input("enter a number : "))
a = 0
for i in range(2,n):
  if(n%i == 0):
    a = 1
    break
if(a==1):
  print(n , "not prime ")
else:
  print(n , " prime ")

#q 16
n = int(input("enter a number : "))

for m in range(1,n+1):
  count = 0
  for i in range(1,n+1):
    if(m%i==0):
     count+=1
  if(count==2):
    print(m , end=" ")

#q 17
n = int(input("enter a number "))
for i in range(1,n+1):
  if(n%i==0):
   print(i , end = " ")

#q 17
n = int(input("enter a number : "))
count = 0
total = 0
temp = n
while(temp>0):
  count+=1
  temp = temp//10
temp = n
while(temp>0):
  rem = temp%10
  total = total+rem**count
  temp = temp//10
if(total == n):
  print("armstrong")
else:
  print("not armstrong")

#q 19
n = int(input("enter a number : "))
temp = n
total = 0
while(temp >0):
  rem = temp%10
  factorial = 1
  for i in range(1,rem+1):
    factorial *=i
  total += factorial
  temp = temp//10
if(total == n):
  print("strong")
else:
  print("not strong")

#q 21
n = int(input("enter a number : "))
sum = 0
for i in range(1,n):
  if(n%i==0):
    sum +=i
if(sum==n):
  print("perfect")
else:
  print("not perfect")

#q 21
n = int(input("enter a number : "))
a = 0
b = 1
for i in range(2,n+1):
  next = a+b
  a = b
  b = next
  print(b , end = " ")

#q 22
value = "01101110"
a = '0'
b = '1'
flipped = ""
for  i in value:
  if i == a:
    flipped += b
  else:
    flipped += a
print (int(flipped))    
